Repository 42-195KM/backend, pull requests merged in 2025-04, with the labels that each got.

#3 feature/#1 : common 모듈 초기 설정
  build.gradle
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/src/main/resources/application.yml
  settings.gradle
Labels: feature

#5 feature/#4 공통 응답 클래스 작성
  common/src/main/java/com/_42195km/msa/common/api/ApiResponse.java
  common/src/main/java/com/_42195km/msa/common/exception/CustomBusinessException.java
  common/src/main/java/com/_42195km/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/_42195km/msa/common/exception/code/CommonErrorCode.java
  common/src/main/java/com/_42195km/msa/common/exception/code/ErrorCode.java
Labels: feature

#10 Feat/#2 create user service
  .gitignore
  common/build.gradle
  common/src/main/java/com/_42195km/msa/common/BaseEntity.java
  common/src/main/java/com/_42195km/msa/common/config/AuditorAwareImpl.java
  common/src/main/java/com/_42195km/msa/common/config/JpaAuditingConfig.java
Labels: feature

#20 feat: docker-compose 를 이용한 db 설정 #17
  docker-compose.yml
  init.sql
Labels: feature

#19 feat: 네이버 컨벤션 적용 #18
  conventions/naver-intellij-formatter.xml
Labels: feature

#26 feat: 크루 게시판 기능 구현
  .gitignore
  common/src/main/java/com/_42195km/msa/common/exception/code/CommonErrorCode.java
  crew-service/build.gradle
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/CreateCommentCommandDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/CreatePostCommandDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/UpdateCommentCommandDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/UpdatePostCommandDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/CommentAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/PostAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/PostWithCommentsAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/mapper/PostMapper.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/service/BoardService.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/Comment.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/Post.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/repository/CommentRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/repository/PostRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/config/GlobalConfig.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/CommentJpaRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/CommentRepositoryImpl.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/PostJpaRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/PostRepositoryImpl.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/controller/BoardController.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/CreateCommentRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/CreatePostRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/GetBoardRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/SearchBoardRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/UpdateCommentRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/UpdatePostRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/CommentResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/PostResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/PostWithCommentsResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/exception/BoardErrorCode.java
  crew-service/src/main/resources/application.properties
  crew-service/src/test/java/com/_42195km/msa/crew/application/service/BoardServiceTest.java
Labels: feature

#36 Feature/#35 - ErrorCode 를 ServiceCode 로 변경하고 정상, 실패흐름 통합
  common/src/main/java/com/_42195km/msa/common/api/ApiResponse.java
  common/src/main/java/com/_42195km/msa/common/code/CommonServiceCode.java
  common/src/main/java/com/_42195km/msa/common/code/ServiceCode.java
  common/src/main/java/com/_42195km/msa/common/exception/CustomBusinessException.java
  common/src/main/java/com/_42195km/msa/common/exception/code/CommonErrorCode.java
  common/src/main/java/com/_42195km/msa/common/exception/code/ErrorCode.java
Labels: feature

#37 Feature/#15 create user service client
  common/src/main/java/com/_42195km/msa/common/api/ApiResponse.java
  common/src/main/java/com/_42195km/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/_42195km/msa/common/exception/code/CommonErrorCode.java
  common/src/main/java/com/_42195km/msa/common/exception/code/ErrorCode.java
  settings.gradle
  user-service/build.gradle
  user-service/gradle/wrapper/gradle-wrapper.jar
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/src/main/java/com/_42195km/msa/user/UserServiceApplication.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/request/CreateUserRequestDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/request/UpdateUserRequestDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/response/CreateUserResponseDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/response/GetAllUserResponseDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/response/GetUserResponseDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/response/SearchUserResponseDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/dto/response/UpdateUserResponseDto.java
  user-service/src/main/java/com/_42195km/msa/user/application/exception/UserException.java
  user-service/src/main/java/com/_42195km/msa/user/application/service/UserService.java
  user-service/src/main/java/com/_42195km/msa/user/application/service/UserServiceImpl.java
  user-service/src/main/java/com/_42195km/msa/user/application/success/UserSuccessCode.java
  user-service/src/main/java/com/_42195km/msa/user/domain/model/Gender.java
  user-service/src/main/java/com/_42195km/msa/user/domain/model/User.java
  user-service/src/main/java/com/_42195km/msa/user/domain/model/UserRole.java
  user-service/src/main/java/com/_42195km/msa/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/config/OptionalNotBlank.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/config/OptionalNotBlankValidator.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/persistence/UserJpaRepository.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/persistence/UserRepositoryImpl.java
  user-service/src/main/java/com/_42195km/msa/user/presentation/controller/UserController.java
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/db/data.sql
  user-service/src/main/resources/db/schema.sql
  user-service/src/main/resources/properties/datasource.yml
  user-service/src/main/resources/properties/jpa.yml
  user-service/src/test/java/com/_42195km/msa/user/UserServiceApplicationTests.java
Labels: feature

#49 Feature/#48 auth token management
  auth-service/build.gradle
  auth-service/src/main/java/com/_42195km/msa/auth/application/dto/request/BlackListRequestDto.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/dto/request/RefreshTokenRequestDto.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/dto/request/UserLogInRequestDto.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/dto/response/AccessTokenReissueResponseDto.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/exception/AuthException.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/service/AuthService.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/service/AuthServiceImpl.java
  auth-service/src/main/java/com/_42195km/msa/auth/application/success/AuthSuccessCode.java
  auth-service/src/main/java/com/_42195km/msa/auth/domain/repository/AuthRepository.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/config/RedisConfig.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/config/SecurityConfig.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/filter/AuthenticationFilter.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/jwt/JwtUtil.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/persistence/AuthJpaRepository.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/persistence/AuthRepositoryImpl.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/persistence/RedisRepository.java
  auth-service/src/main/java/com/_42195km/msa/auth/infrastructure/persistence/RedisRepositoryImpl.java
  auth-service/src/main/java/com/_42195km/msa/auth/presentation/controller/AuthController.java
  auth-service/src/main/java/com/_42195km/msa/auth/presentation/dto/request/TokenRequestDto.java
  auth-service/src/main/java/com/_42195km/msa/auth/presentation/dto/response/ValidateTokenResponse.java
  auth-service/src/main/resources/application.yml
  auth-service/src/main/resources/db/data.sql
  auth-service/src/main/resources/properties/redis.yml
  common/src/main/java/com/_42195km/msa/common/aop/CheckPermission.java
  common/src/main/java/com/_42195km/msa/common/aop/PermissionAspect.java
  common/src/main/java/com/_42195km/msa/common/aop/PermissionException.java
  docker-compose.yml
  gateway/build.gradle
  gateway/src/main/java/com/_42195km/msa/gateway/config/SecurityConfig.java
  gateway/src/main/java/com/_42195km/msa/gateway/config/WebClientConfig.java
  gateway/src/main/java/com/_42195km/msa/gateway/dto/request/TokenRequestDto.java
  gateway/src/main/java/com/_42195km/msa/gateway/dto/response/ValidateTokenResponseDto.java
  gateway/src/main/java/com/_42195km/msa/gateway/filter/AuthenticationFilter.java
  gateway/src/main/java/com/_42195km/msa/gateway/util/JwtUtil.java
  user-service/src/main/java/com/_42195km/msa/user/presentation/controller/UserController.java
Labels: enhancement, feature

#57 Feature/#56 : @UserInfo 애노테이션 추가
  common/src/main/java/com/_42195km/msa/common/config/WebConfig.java
  common/src/main/java/com/_42195km/msa/common/resolver/UserInfo.java
  common/src/main/java/com/_42195km/msa/common/resolver/UserInfoArgumentResolver.java
  common/src/main/java/com/_42195km/msa/common/resolver/UserInfoDto.java
Labels: feature

#53 Feature/#9 crew cruds
  common/src/main/java/com/_42195km/msa/common/code/CommonServiceCode.java
  crew-service/src/main/java/com/_42195km/msa/crew/CrewApplication.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/CreateCrewAppRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/HandleCrewJoinAppRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/UpdateCrewAppRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/CreateCrewAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/ExpelCrewMemberAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/GetSpecificCrewAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/GetSpecificCrewMemberAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/HandleCrewJoinAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/JoinCrewAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/SearchCrewAppPagingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/SearchCrewMemberAppPagingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/UpdateCrewAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/exception/CrewBusinessException.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/exception/CrewServiceCode.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/service/CrewService.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/Crew.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeeting.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeetingMember.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeetingMemberMapping.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMember.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMemberMapping.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/repository/CrewRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/CrewJpaRepository.java
  crew-service/src/main/java/com/_42195km/msa/crew/infrastructure/persistence/CrewRepositoryImpl.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/controller/CrewController.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/CreateCrewRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/HandleCrewJoinRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/UpdateCrewRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/CreateCrewResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/ExpelCrewMemberResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/GetSpecificCrewMemberResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/GetSpecificCrewResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/HandleCrewJoinResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/JoinCrewResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/SearchCrewMemberPagingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/SearchCrewPagingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/UpdateCrewResponseDto.java
Labels: feature

#61 Feature/#59 crewmeeting
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/CreateCrewMeetingAppRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/request/UpdateCrewMeetingAppRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/CreateCrewMeetingAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/GetSpecificCrewMeetingAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/HandleCrewJoinAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/ParticipateCrewMeetingAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/dto/response/UpdateCrewMeetingAppResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/exception/CrewServiceCode.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/service/CrewService.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/Crew.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeeting.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeetingMember.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMeetingMemberMapping.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMember.java
  crew-service/src/main/java/com/_42195km/msa/crew/domain/model/CrewMemberMapping.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/controller/CrewController.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/CreateCrewMeetingRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/request/UpdateCrewMeetingRequestDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/CreateCrewMeetingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/GetSpecificCrewMeetingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/ParticipateCrewMeetingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/SearchCrewMeetingPagingResponseDto.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/dto/response/UpdateCrewMeetingResponseDto.java
Labels: feature

#58 Feature/#46 competition apply
  common/src/main/generated/com/_42195km/msa/common/QBaseEntity.java
  competition-service/build.gradle
  competition-service/src/main/java/com/_42195km/msa/competitionservice/CompetitionServiceApplication.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/dto/CompleteAppDto.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/ApplicationSagaEvent.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/ApplicationStep.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/CancellationSagaEvent.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/CompetitionApplicationEvent.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/PaymentSagaEvent.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/event/SagaEvent.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/CompetitionService.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/SagaService.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/Competition.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/CompetitionParticipantMapping.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/Participant.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/ParticipantDetail.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/SagaState.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/SagaStatus.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/SagaStep.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/repository/CompetitionRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/repository/ParticipantDetailRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/config/GlobalConfig.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/config/KafkaConfig.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/config/RedisConfig.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/CompetitionApplyNotificationDto.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/CompetitionSagaOrchestrator.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/NotificationEventProducer.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/SagaEventConsumer.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/CompetitionJpaRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/CompetitionParticipantMappingJpaRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/CompetitionParticipantMappingRepositoryImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/CompetitionRepositoryImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/ParticipantDetailJpaRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/ParticipantDetailRepositoryImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/ParticipantJpaRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/ParticipantRepositoryImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/persistence/SagaStateRepository.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/controller/CompetitionController.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/controller/ParticipantController.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/dto/request/ApplyCompetitionRequestDto.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/dto/request/CancelParticipantRequestDto.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/dto/response/ParticipantResponseDto.java
  competition-service/src/main/resources/application-test.properties
  competition-service/src/main/resources/application.properties
  competition-service/src/test/java/com/_42195km/msa/competitionservice/presentation/controller/CompetitionControllerAPITest.java
  crew-service/build.gradle
  crew-service/src/main/java/com/_42195km/msa/crew/CrewApplication.java
  crew-service/src/main/java/com/_42195km/msa/crew/application/exception/BoardServiceCode.java
  crew-service/src/main/java/com/_42195km/msa/crew/presentation/controller/BoardController.java
  crew-service/src/main/resources/application-test.properties
  crew-service/src/main/resources/application.properties
  crew-service/src/test/java/com/_42195km/msa/crew/presentation/controller/BoardControllerAPITest.java
  docker-compose.yml
Labels: feature

#70 Feature/#69 refactoring
  auth-service/src/main/java/com/_42195km/msa/auth/domain/model/Auth.java
  auth-service/src/main/resources/db/data.sql
  auth-service/src/main/resources/db/schema.sql
  auth-service/src/main/resources/properties/datasource.yml
  ranking-service/src/main/java/com/_42195km/msa/rankingservice/domain/model/Ranking.java
  ranking-service/src/main/java/com/_42195km/msa/rankingservice/domain/model/RankingDetail.java
  ranking-service/src/main/resources/db/schema.sql
  ranking-service/src/main/resources/properties/datasource.yml
  user-service/src/main/java/com/_42195km/msa/user/domain/model/User.java
  user-service/src/main/java/com/_42195km/msa/user/infrastructure/config/KafkaConfig.java
  user-service/src/main/resources/db/schema.sql
  user-service/src/main/resources/properties/datasource.yml
Labels: bug, enhancement

#79 refactor: 디자인 패턴 적용
  competition-service/build.gradle
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/dto/request/CreateCompetitionCommandDto.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/facade/CompetitionApplicationFacade.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/mapper/ParticipantMapper.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/CompetitionService.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/CompetitionServiceImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/ParticipantService.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/ParticipantServiceImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/SagaService.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/application/service/SagaServiceImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/ApplicationStep.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/Competition.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/CompetitionParticipantMapping.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/domain/model/PaymentInfo.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/config/KafkaConfig.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/EventPublisher.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/KafkaEventPublisher.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/SagaEventConsumer.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/SagaEventPublisher.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/SagaOrchestrator.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/infrastructure/messaging/SagaOrchestratorImpl.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/controller/CompetitionController.java
  competition-service/src/main/java/com/_42195km/msa/competitionservice/presentation/controller/ParticipantController.java
  competition-service/src/main/resources/application.properties
  competition-service/src/test/java/com/_42195km/msa/competitionservice/CompetitionServiceImplApplicationTests.java
  competition-service/src/test/java/com/_42195km/msa/competitionservice/application/service/CompetitionServiceImplTest.java
  competition-service/src/test/java/com/_42195km/msa/competitionservice/application/service/ParticipantServiceTest.java
  competition-service/src/test/java/com/_42195km/msa/competitionservice/presentation/controller/CompetitionControllerAPITest.java
  crew-service/build.gradle
  crew-service/src/main/resources/application-test.properties
  crew-service/src/test/java/com/_42195km/msa/crew/application/service/BoardServiceTest.java
Labels: enhancement

#80 Test/alertconsumer
  alert-service/build.gradle
  alert-service/src/main/resources/application-test.yml
  alert-service/src/test/java/com/_42195km/alertservice/AchieveKafkaConsumerTest.java
  alert-service/src/test/java/com/_42195km/alertservice/AlertServiceApplicationTests.java
  alert-service/src/test/java/com/_42195km/alertservice/CompetionKafkaConsumerTest.java
  alert-service/src/test/java/com/_42195km/alertservice/KafkaConsumerSendAlertTest.java
  alert-service/src/test/java/com/_42195km/alertservice/RetryKafkaConsumerTest.java
Labels: bug

#81 feature: 모니터링 설정
  .gitignore
  competition-service/src/main/resources/application.properties
  competition-service/src/main/resources/logback-spring.xml
  docker-compose.yml
  grafana/provisioning/datasources/datasources.yml
  loki/config.yaml
  prometheus.yml
  prometheus/prometheus.yml
Labels: feature
